site_name: 深度学习与医学影像
site_url: http://medical-imaging.hackerphysics.com

theme:
    name: material
    logo: images/medical-imaging.png
    favicon: images/medical-imaging.png
    features:
      - navigation.expand
      - navigation.top
      - navigation.tabs
      - search.suggest
      - toc.integrate
      - content.code.annotate
nav:
    - '前言': 'index.md'
    
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js